# Generated by Django 2.2.12 on 2020-04-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post1_post2_post3_post4_post5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post2',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post3',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post4',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post5',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
        migrations.DeleteModel(
            name='Post1',
        ),
        migrations.DeleteModel(
            name='Post2',
        ),
        migrations.DeleteModel(
            name='Post3',
        ),
        migrations.DeleteModel(
            name='Post4',
        ),
        migrations.DeleteModel(
            name='Post5',
        ),
    ]
